# system setup
sudo: required

# setup language
language: go
go:
  - "1.12"

install:
  # download our task runner
  - go get github.com/alecaivazis/run
  # install the ci dependencies
  - run install:ci

script:
  # install the dependencies
  - run install
  # generate and report the test coverage
  - run tests:coverage

before_deploy:
  # build the binaries
  - run build

deploy:
  # only deploy on tagged releases
  on:
    tags: true
  # we need to push a github release with this tag
  provider: script
  skip_cleanup: true
  script: run deploy
